#+STARTUP: indent

* File type handling
The section deals with handling varying file formats and types like
~json~, ~yaml~, ~toml~ etc.

** Handling json files
~json-mode~ provides a major mode for editing ~json~ format files in emacs and it extends the builtin js-mode to add better syntax highlighting for JSON with some nice editing keybindings.
#+begin_src emacs-lisp
(use-package json-mode
  :ensure json-mode
  :delight "J"
  :config (bind-keys :map json-mode-map
                     ("C-c i" . json-mode-beautify))
  :mode ("\\.\\(json\\)$" . json-mode))
#+end_src

** Handling yaml files
~yaml-mode~ package is an emacs major mode for editing files in the YAML data serialization format.
#+begin_src emacs-lisp
;; installing yaml-mode for editing yaml format files
;;
;; (use-package yaml-mode
;;   :mode ("\\.\\(yml\\|yaml\\|\\config\\|sls\\)$" . yaml-mode)
;;   :ensure yaml-mode
;;   :defer t)

(use-package yaml-mode
  :straight t
  ;; :mode "\\.yml\\'"
  :mode "(\\.\\(yml?\\|yaml\\|config\\|sls\\)\\'"
  :config
  ;; (add-hook 'yaml-mode-hook 'smartparens-mode)
  (add-hook 'yaml-mode-hook 'highlight-indent-guides-mode)
  (add-to-list 'auto-mode-alist '("\\.yml\\'" . yaml-mode)))
#+end_src

** yaml-pro
~yaml-pro~ has tools for editing YAML leveraging tree-sitter/parser.

#+begin_src emacs-lisp :lexical no
;; Edit YAML in Emacs like a pro
(use-package yaml-pro
    :straight t)
#+end_src

** Handling toml files
This is an Emacs Mojor mode for editing the TOML files. =TOML= files are pretty common in Rust as the package configurations are always in that format named as _Cargo.toml_.
#+begin_src emacs-lisp
;; editing TOML files
;; Usefule specifically for Cargo.toml and other config files
(use-package toml-mode
  :quelpa
  (:fetcher github :repo "dryman/toml-mode.el"))
#+end_src


** Treesitter
Tree-sitter is a parser generator tool and an incremental parsing library. It
can build a concrete syntax tree for a source file and efficiently update the
syntax tree as the source file is edited.

=tree-sitter= is an Emacs binding for Tree-sitter, an incremental parsing system.
#+begin_src emacs-lisp :lexical no
;; tree-sitter
;; This is an emacs binding for Treesitter
(use-package tree-sitter
  :ensure t
  :config
  ;; activate tree-sitter on any buffer containing the code
  ;; for which it has a valid parser available
  (require 'tree-sitter-langs)
  (global-tree-sitter-mode)
  ;; we can easily observe the difference tree-sitter-hl-mode makes
  ;; for python, ts or tsx by switching on and off
  (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode))
#+end_src

The  package ~tree-sitter-langs~  is a  convenient language  bundle for  the Emacs
package  tree-sitter. It  serves  as an  interim  distribution mechanism,  until
tree-sitter  is   widespread  enough   for  language-specific  major   modes  to
incorporate its functionalities.

#+begin_src emacs-lisp :tangle yes
;; Language bundle for Emacs's tree-sitter package
(use-package tree-sitter-langs
  :ensure t
  :after tree-sitter
  :quelpa (tree-stter-langs :fetcher github :repo "emacs-tree-sitter/tree-sitter-langs"))
#+end_src

For installing all the native language specific tree sitters, we can use the
package ~treesit-auto~. It automatically pick between TreeSitter and default major
modes in Emacs 29+.
#+begin_src emacs-lisp :lexical no
(use-package treesit-auto
  :quelpa (treesit-auto :fetcher github :repo "renzmann/treesit-auto")
  :custom
  (treesit-auto-install 'prompt)
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode))
#+end_src

* Tree-Sitter Support
#+begin_src emacs-lisp :lexical no
;; tree-sitter language support
(use-package treesit
  :straight (:type built-in)
  :if (featurep 'treesit)
  :config
  (setq treesit-language-source-alist
	    (mapcar
	     (lambda (item)
	       (let ((lang (nth 0 item))
		         (url (nth 1 item))
		         (rev (nth 2 item))
		         (source-dir (nth 3 item)))
	         `(,lang ,url ,rev ,source-dir
		             ,(executable-find "gcc") ,(executable-find "c++"))))
	     '((bash "https://github.com/tree-sitter/tree-sitter-bash")
	       (cmake "https://github.com/uyha/tree-sitter-cmake")
	       (css "https://github.com/tree-sitter/tree-sitter-css")
	       (elisp "https://github.com/Wilfred/tree-sitter-elisp")
	       (go "https://github.com/tree-sitter/tree-sitter-go")
	       (html "https://github.com/tree-sitter/tree-sitter-html")
	       (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
	       (json "https://github.com/tree-sitter/tree-sitter-json")
	       (make "https://github.com/alemuller/tree-sitter-make")
	       (markdown "https://github.com/ikatyang/tree-sitter-markdown")
	       (python "https://github.com/tree-sitter/tree-sitter-python")
           (rust "https://github.com/tree-sitter/tree-sitter-rust")
	       (toml "https://github.com/tree-sitter/tree-sitter-toml")
	       (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
	       (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
	       (yaml "https://github.com/ikatyang/tree-sitter-yaml"))))
  (setq treesit-font-lock-level 4)
  (setq major-mode-remap-alist
	    '((typescript-mode . typescript-ts-mode)
	      (js-mode . javascript-ts-mode)
	      (python-mode . python-ts-mode)
          (rust-mode . rust-ts-mode)
	      (json-mode . json-ts-mode)))
  (cl-loop for (old-mode . new-mode) in major-mode-remap-alist
	       ;; do (my/set-smartparens-indent new-mode)
	       do (set (intern (concat (symbol-name new-mode) "-hook"))
		           (list
		            (eval `(lambda ()
			                 (run-hooks
			                  ',(intern (concat (symbol-name old-mode) "-hook")))))))))
#+end_src

treesit-fold uses treesit.el for folding.
#+begin_src emacs-lisp :lexical no
;; treesit-fold uses treesit.el for folding.
(use-package treesit-fold
  :straight (treesit-fold :type git :host github :repo "emacs-tree-sitter/treesit-fold")
  :commands (treesit-fold-mode))
#+end_src
