#!/usr/bin/env perl

#
# Latexmk configuration template for tex to pdf
# rename this file to .latexmkrc and place under home directory
#

# PDF-generating modes are:
# 1: pdflatex, as specified by $pdflatex variable (still largely in use)
# 2: postscript conversion, as specified by the $ps2pdf variable (useless)
# 3: dvi conversion, as specified by the $dvipdf variable (useless)
# 4: lualatex, as specified by the $lualatex variable (best)
# 5: xelatex, as specified by the $xelatex variable (second best)
$pdf_mode = 1;

# If nonzero, continue processing past minor latex errors including
# unrecognized cross references
$force_mode = 0;

$show_time = 1;           # Show used CPU time
$bibtex_use = 1;          # Use bibtex if the .bib file exists

# $emulate_aux = 1;       # do not supply the -aux-directory
# $out_dir = 'build';
# $aux_dir = 'aux';
$tmpdir  = "/tmp";

# Needed for the dot2texi package which invokes GraphViz.
# Latex file editing >latexmk -pvc -pdf foo.tex
$latex = 'xetex -interaction=nonstopmode -shell-escape -synctex=1';
$xelatex = 'xelatex -interaction=nonstopmode -shell-escape -synctex=1';
$lualatex = 'lualatex %O --shell-escape %S -f';
$pdflatex = 'pdflatex -interaction=nonstopmode -shell-escape -synctex=1 %O %S';
$pdf_previewer = "open -ga /Applications/Skim.app";   # Use default PDF viewer to open files


# Mac OS
# remove files with the following file extentions
# (as well as the default ones) when using "latexmk -c" or "latexmk -C"
#
$clean_ext = "paux lox pdfsync out synctex.gz run.xml %R-blx.bib lol bbl bcf fdb_latexmk out";
$cleanup_includes_cusdep_generated = 1;
