#+TITLE: Learning ORG
#+AUTHOR: Sampath Singamsetty

* ORG Mode shortcuts

Within any section of a large org file with multiple sections pressing ~C-x n s~
will invoke ~org-narrow-to-subtree~ and once the work is done we can come back to
the original buffer by pressing ~C-x n w~ which invokes ~widen~. The same is a part
of the section ref:transitioning.


* Transitioning between the sections <<transitioning>>
   With all the existing standard Emacs movement keybindings below are helpful:

   - =C-c C-n= :: To move to the next section header (or =C-M-n=)
   - =C-c C-p= :: To move to the previous section header (=C-M-p=)
   - =C-c C-f= :: To move to header at the same level (on
                top-level? go to the next top-level)
   - =C-c C-b= :: To move to previous header at same level
   - =C-c C-^= :: To move to the parent header (yeah, odd binding)

   Nice features to focus on a section:

   - =C-x n s= :: To narrow to the org-mode section
   - =C-x n w= :: To widen back to the full text

* Standard important key bindings
Some key bindings are very handy and few such are listed here:

- =C-h i m pkg-name= :: To go through the documentation of a package

* AucTeX Tips
Using =auctex= for document editing provides some powerful features for editing
and previewing documents. Here’s a list of what can be done:

- =C-c C-p C-d= :: Preview a section right inside the buffer
- =C-c C-p C-b= :: Preview the entire buffer
- =C-c C-c=     :: Compile into a buffer

** Formatting
Type ~C-x f~ which will prompt to enter fill-width:

#+begin_example
C-x f

Change fill-column from 70 to (default 461):
#+end_example

Now press ~C-u M-q~ to format the text to fill the width.

We can instruct Emacs to automatically fill text as we write by enabling ~M-x
auto-fill-mode~, but it is better to restrict to =text-mode=.

* Regular Emacs Tips and Tricks
** Playing with Macros
We can record a set of actions that we may then apply to a selected region. As
an example, consider transforming the below lines:

#+begin_example
One
Two
Three
Four
Five
#+end_example

In order to transform the above into below:
#+begin_example
- One
- Two
- Three
- Four
- Five
#+end_example

+ Place cursor on very first line and start recording a new keyboard macro by
  typing: =C-x (=.
+ Go to the beginning of the line with =C-a= and then insert a hyphen followed by
  a space and then move down one line so that the cursor resides on second line.
+ Stop recording the macro with =C-x )=.
+ Now select the rest of lines from second line onwards and apply the newly
  recorded macro to the selected region by pressing =C-x C-k r=.


* Getting help

help:org-format-latex-header
help:org-latex-default-packages-alist
help:org-latex-packages-alist
help:org-latex-pdf-process
